### PR TITLE
Change category feature

### PR DESCRIPTION
**Pull request by xdml**
This allows user to change Department / Category of the ticket. So user can "reassign" ticket to another department and category.

### CODE REVIEW

**Comment by evereux** [comment]
I can implement this but only if we make this an optional feature within the administration section.

    user_change_category = False
    # If true, any user can change_category

    super_user_change_category = False
    # if true, only admin and super_user can change category

Some companies might not want tickets bouncing all over the place. 

Can we stick to the department / category nomenclature please? Having that and your own queue nomenclature will make things confusing for others looking at the source. I understand your goal here but others may not. I'd like that to be consistent and was planning on changing what's been done at some point.

Big thanks again for your efforts here.

Also, I've made some significant changes over the past few days. I'm migrating over to bootstrap 4 and changing some layouts. So merging may prove interesting for this git noob.

obviously, some more work to be done ;-)
Screenshot at 2019-11-05 14-11-55


I've made some changes to the layout

**Comment by xdml** [comment]
Thank you for review. I'll try to modify it as you proposed, including extra configuration.

Is it acceptable to do it only on user level (`user_change_category = False`) and leave `admin` and `super_admin` as TODO for next release?

No problem to get rid of my naming convention, and use "category" instead. I did it for having it quicker to find combination of Department / Category and prepared search API for it, so user is able to type in and it searches for the combination.

Will you be fine to leave there the "virtual" model and API, but renamed to departmetncategory? Or what is your suggestion here?

Do you plan to use " / " as department category separator instead of " - " like it uses currently?

Sorry for many questions, but feel it should be discussed first and later I should rewrite it and test. I expect it will take some time, to rewrite and do some tests...

**Comment by evereux** [comment]
> Thank you for review. I'll try to modify it as you proposed, including extra configuration.
> 
> Is it acceptable to do it only on user level (`user_change_category = False`) and leave `admin` and `super_admin` as TODO for next release?

Thinking about this further. I think it's fine to just have that option only. Makes the most sense to me.

> No problem to get rid of my naming convention, and use "category" instead. I did it for having it quicker to find combination of Department / Category and prepared search API for it, so user is able to type in and it searches for the combination.
> 
> Will you be fine to leave there the "virtual" model and API, but renamed to departmetncategory? Or what is your suggestion here?

`department_category` sounds good to me.


> Do you plan to use " / " as department category separator instead of " - " like it uses currently?

For web page display purposes I think so yes. I think that reads better. We can then use hyphens in the department / category name and it won't look weird.

> Sorry for many questions, but feel it should be discussed first and later I should rewrite it and test. I expect it will take some time, to rewrite and do some tests...

No need to say sorry. All valid questions.

**Comment by evereux** [comment]
> > Thank you for review. I'll try to modify it as you proposed, including extra configuration.
> > Is it acceptable to do it only on user level (`user_change_category = False`) and leave `admin` and `super_admin` as TODO for next release?
> 
> Thinking about this further. I think it's fine to just have that option only. Makes the most sense to me.

Have you looked at this at all yet? I can add this after the pull request is merged if you like.

There's some merge conflicts as a result of the updates I've done now. I can sort those out when I look into this pull request.

**Comment by xdml** [comment]
Not yet, probably will look at it this week, no problem with conflicts, I will try to resolve it in my repository a prepare for you. Will comment it when it is ready. But I expect, that I will do first changes at my own copy a do testing and later will push changes into this branch, so at the moment I need more time.

**Comment by xdml** [comment]
**Updated**

So finally I changed naming convention so now it is not using queue at all parts of flicket, including sorts.

Added configuration options:

- `change_category` if `True` the feature is enabled.
- `change_category_only_admin_or_super_user` if `True` the feature is enabled only for admins and super users, regular users will not be allowed to use it.

If feature is not allowed or user does not have admin or super user privileges, no link (button like) is visible and the view will return 404.

Please review and let me know, if you agree with the change.

I made small changes in other parts as well, like small bugfixies.

Because of configuration options, it is necessary to execute:

```
python manage.py db upgrade
```

to upgrade FlicketConfig model.

**Pull request merged**
